name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, nixos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Package project
        run: npm run package

      - name: Publish to GitHub
        run: npm publish

      - name: Publish to NPM
        run: npm publish --registry=https://registry.npmjs.org/

      - name: Publish to Deno.land
        run: deno publish

      - name: Publish to Docker
        run: docker build -t myproject . && docker push myproject

      - name: Publish to Winget
        run: winget create myproject

      - name: Publish to Nixpkg
        run: nix-build release.nix

      - name: Generate changelog
        run: npm run changelog

      - name: Bump version
        run: npm version patch

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:windows

      - name: Build for NixOS
        if: matrix.os == 'nixos-latest'
        run: npm run build:nixos

      - name: Build for Linux Flatpak
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:flatpak

      - name: Build for MacOS
        if: matrix.os == 'macos-latest'
        run: npm run build:macos

      - name: Build for iOS
        if: matrix.os == 'macos-latest'
        run: npm run build:ios

      - name: Build for Android
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:android

      - name: Generate documentation
        run: npm run generate-docs

      - name: Publish documentation
        run: npm run publish-docs
